### ISSUE TITLE
Degree typo

### ISSUE THREAD

**Issue by TsumaHibiki** [123standup/LazyAutoForm#2]
36 degree would be written as 36 but not 36.0

**Comment by TsumaHibiki** [comment]
Automatically solved due to min body temp

**Comment by TsumaHibiki** [comment]
Even if the min body temp is below 36, the issue should still be solved by the new round10(temp, -1) function.

**Comment by abckf654** [comment]
Issue can be solved by using toFixed(1) in Update index.html #8 pull request.
